### ISSUE TITLE
QueryExecutor throws error on parsing Intents from text in interactive mode

### ISSUE THREAD

**Issue by errantlinguist** [articulab/sempre#5]
When running the `edu.cmu.mld.saranlu.SaraNLUAgent`, typing e.g. "hello" results in an error from `edu.cmu.mld.saranlu.QueryExecutor`:

	java.lang.RuntimeException: unknown formula type: class edu.stanford.nlp.sempre.intents.GreetIntent
		at edu.cmu.mld.saranlu.QueryExecutor.queryFormula(QueryExecutor.java:123)
		at edu.cmu.mld.saranlu.QueryExecutor.execute(QueryExecutor.java:129)
		at edu.cmu.mld.saranlu.SaraNLUAgent.handleUtterance(SaraNLUAgent.java:268)
		at edu.cmu.mld.saranlu.SaraNLUAgent.processQuery(SaraNLUAgent.java:207)
		at edu.cmu.mld.saranlu.SaraNLUAgent.processQuery(SaraNLUAgent.java:192)
		at edu.cmu.mld.saranlu.SaraNLUAgent.runInteractivePrompt(SaraNLUAgent.java:172)
		at edu.cmu.mld.saranlu.Main.run(Main.java:65)
		at fig.exec.Execution.runWithObjArray(Execution.java:337)
		at fig.exec.Execution.run(Execution.java:325)
		at edu.cmu.mld.saranlu.Main.main(Main.java:81)

**Comment by errantlinguist** [comment]
Migrated to https://github.com/articulab/inmind-sempre-nlu/issues/5
